#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#
#spring:
#  datasource:
#    password:
#    url: jdbc:mysql://localhost:3306/we-care
#    username: root
#  jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
#     show-sql: true
#
#  mail:
#    host: localhost
#    port: 1025
#    username: layendiaye195@gmail.com
#    password:
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
#
